apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: chat-app
type: Opaque
data:
  JWT_SECRET: c2VjdXJlX2p3dF9zZWNyZXQ=  # base64 encoded 'secure_jwt_secret'
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6YWRtaW5AbW9uZ286MjcwMTcvY2hhdEFwcD9hdXRoU291cmNlPWFkbWluJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ== # base64 encoded 'mongodb://root:admin@mongo:27017/chatApp?authSource=admin&retryWrites=true&w=majority'